[package]
edition = "2021"
name = "room-api"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"]}
async-trait = "0.1.68"
fred = { version = "6.3.0", features = ["enable-rustls"] }
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
futures = "0.3.28"
http = "0.2.9"
http-serde = "1.1.2"
mysql_async = { version = "0.32.2", default-features = false, features = ["default-rustls"] }
mysql_common = "0.30.4"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.13.1", default-features = false, features = [
  "napi8",
  "tokio_rt",
  "anyhow",
  "serde-json",
] }
napi-derive = "2.13.0"
once_cell = "1.18.0"
regex = "1.8.4"
seahash = "4.1.0"
seq-macro = "0.3.3"
serde = { version = "1.0.164", features = ["rc"] }
serde_json = "1.0.96"
serde_qs = "0.12.0"
serde_repr = "0.1.12"
shaku = "0.6.1"
surf = { version = "2.3.2", features = [
  "encoding",
  "h1-client-rustls",
], default-features = false }
thiserror = "1.0.40"
time = { version = "0.3.22" }
tokio = { version = "1.28.2", features = [
  "parking_lot",
  "rt-multi-thread",
  "macros",
] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url-escape = "0.1.1"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
opt-level = 3

[dev-dependencies]
fred = { version = "6.3.0", features = ["enable-rustls", "mocks"] }
pretty_assertions = "1.3.0"
tokio-test = "0.4.2"
rstest = "0.17.0"
rstest_reuse = "0.5.0"
